In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('daibetes.xlsx')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
X = df.drop('Outcome', axis = 1)
y= df['Outcome'].values
print(df.shape, X.shape, y.shape)

(768, 9) (768, 8) (768,)

In [19]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size =0.2 , random_state = 32)
scaler_std = StandardScaler()
scaler_min = MinMaxScaler()
X_train = scaler_std.fit_transform(X_train)
X_test = scaler_std.transform(X_test)
X_train = scaler_min.fit_transform(X_train)
X_test = scaler_min.transform(X_test)

In [28]:
preg_mean = round(X_train.Pregnancies.mean(),2)
preg_std = round(X_train.Pregnancies.std(),2)
print(preg_mean)
print(preg_std)

3.87
3.39

In [32]:
X_train['preg_scaled'] = (X_train['Pregnancies']-preg_mean)/ preg_std

In [33]:
X_train.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,preg_scaler,preg_scaled
196,1,105,58,0,0,24.3,0.187,21,-0.846608,-0.846608
22,7,196,90,0,0,39.8,0.451,41,0.923304,0.923304
137,0,93,60,25,92,28.7,0.532,22,-1.141593,-1.141593
469,6,154,78,41,140,46.1,0.571,27,0.628319,0.628319
627,0,132,78,0,0,32.4,0.393,21,-1.141593,-1.141593

In [35]:
print("Mean of scaled Pregnancies column is:", round(X_train.preg_scaled.mean()))
print("Standard deviation of scaled Pregnancies column is:", round(X_train.preg_scaled.std()))

Mean of scaled Pregnancies column is: 0
Standard deviation of scaled Pregnancies column is: 1

In [36]:
gl_min = X_train['Glucose'].min()
gl_max = X_train['Glucose'].max()
X_train['gl_norm'] = (X_train['Glucose'] - gl_min)/ (gl_max - gl_min)

In [37]:
X_train.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,preg_scaler,preg_scaled,gl_norm
196,1,105,58,0,0,24.3,0.187,21,-0.846608,-0.846608,0.527638
22,7,196,90,0,0,39.8,0.451,41,0.923304,0.923304,0.984925
137,0,93,60,25,92,28.7,0.532,22,-1.141593,-1.141593,0.467337
469,6,154,78,41,140,46.1,0.571,27,0.628319,0.628319,0.773869
627,0,132,78,0,0,32.4,0.393,21,-1.141593,-1.141593,0.663317

In [38]:
X_train.gl_norm.min()

np.float64(0.0)

In [39]:
X_train.gl_norm.max()

np.float64(1.0)

from sklearn.svm import SVC
svm = SVC()

In [21]:
svm.fit(X_train, y_train)

SVC()

In [22]:
y_pred_svm = svm.predict(X_test)
y_pred_svm

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0])

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
matrix = confusion_matrix(y_test, y_pred_svm)
acc = accuracy_score(y_test, y_pred_svm)
report = classification_report(y_test, y_pred_svm)
print(matrix)
print(acc)
print(report)

[[92  7]
 [21 34]]
0.8181818181818182
              precision    recall  f1-score   support

           0       0.81      0.93      0.87        99
           1       0.83      0.62      0.71        55

    accuracy                           0.82       154
   macro avg       0.82      0.77      0.79       154
weighted avg       0.82      0.82      0.81       154